/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas.de.menu.anubis.Ventas.CrearVenta;

import conexion.bd;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import pantallas.de.menu.anubis.Empleados_menu;
import pantallas.de.menu.anubis.Inventario.Inventario;
import pantallas.de.menu.anubis.Render;
import pantallas.de.menu.anubis.clientes.Registrar_clientes;
import pantallas.de.menu.anubis.modificar_empleados;
/**
 *
 * @author braya
 */
public class Ventas extends javax.swing.JInternalFrame {
    DefaultTableModel dtm;
    Registrar_clientes rc = new Registrar_clientes();
    modificar_ventas mv = new modificar_ventas();
    int datos_clientes_val = 0;
    int datos_de_productos_val = 0;
    Thread hilo;
    DefaultTableModel dtm2;
    int verificar = 0;
    int verificar1 = 0;
    int verificar_productos = 0;
    int total = 0; 
    //informacion de productos
    String nombre;
    int cantidad;
    String precio;
    //factura
    int numero_fac = 0;
    int neto = 0;
    int total1;
    int cantida_final =0;
    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        CargarDatosCliente();
        Cargar_Datos_Facturas();
        CargarDatosDeProductos();
        jTable2.setVisible(false);
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while(true){
                    // Pero usamos un truco y hacemos un ciclo infinito
                    try {
                        // En él, hacemos que el hilo duerma
                        Thread.sleep(1000);
                        // Y después realizamos las operaciones
                        ActualizarDatosDeVentas();
                        
                        // Así, se da la impresión de que se ejecuta cada cierto tiempo
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        hilo = new Thread(runnable);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallas/de/menu/anubis/Ventas/CrearVenta/Imagenes/perfil (2).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 30, 30));

        jTextField1.setEditable(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 170, 30));

        jTextField2.setEditable(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 170, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallas/de/menu/anubis/Ventas/CrearVenta/Imagenes/llaves.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 30, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallas/de/menu/anubis/Ventas/CrearVenta/Imagenes/grupo (1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 30, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 170, 30));

        jButton1.setText("Agregar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, 30));

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 60, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallas/de/menu/anubis/Ventas/CrearVenta/Imagenes/porcentaje (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallas/de/menu/anubis/Ventas/CrearVenta/Imagenes/simbolo-de-dolar.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 20, 30));

        jTextField4.setEditable(false);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TOTAL ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IMPUESTO ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 280, 30));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Imprimir factura ");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallas/de/menu/anubis/imagenes_para_informacion_de_empleados/salvar.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("IDENTIFICACION: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 30));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 130, 30));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 560, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantalla/de/carga/img/7jQpLf.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 690));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jButton3.setText("BUSCAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BUSCAR PRODUCTO: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(1459, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 1850, 690));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        rc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        datos_clientes_val = 1;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        datos_de_productos_val = 1;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int column = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTable1.getRowHeight();
        if(row<jTable1.getColumnCount() && row >= 0 && column < jTable1.getColumnCount() && column >=0){
            Object value = jTable1.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                if(boton.getName().equals("A")){
                    if(evt.getClickCount() == 2){
                        nombre = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
                        cantidad = 1;
                        try {
                            conexion.bd cbd = new bd();
                            cbd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                            cbd.setUsuario("root");
                            cbd.setContrasena("");
                            Connection con = cbd.getConexion();
                            Statement s = con.createStatement();
                            ResultSet rs = s.executeQuery("SELECT * FROM inventario WHERE ID = '"+jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()+"'");
                            if(rs.next()){
                                precio = rs.getString(6);
                            }
                            rs.close();
                            //----------------------
                            conexion.bd cbd1 = new bd();
                            cbd1.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                            cbd1.setUsuario("root");
                            cbd1.setContrasena("");
                            Connection con1 = cbd1.getConexion();
                            Statement s1 = con.createStatement();
                            ResultSet rs1 = s1.executeQuery("SELECT * FROM guardar_compra WHERE nombre= '"+nombre+"'");
                            if(rs1.next()){
                                System.out.println("pantallas.de.menu.anubis.Ventas.CrearVenta.Ventas.jTable1MouseClicked()");
                            }else{
                                PreparedStatement pst;
                                try {
                                    pst = con1.prepareStatement("INSERT INTO guardar_compra(nombre, cantidad, precio) VALUES (?,?,?)");
                                    pst.setString(1, nombre);
                                    pst.setInt(2, cantidad);
                                    pst.setString(3, precio);
                                    pst.executeUpdate();
                                } catch (SQLException ex) {
                                    Logger.getLogger(Registrar_clientes.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                cargar_datos_de_compra();
                                verificar = 1;
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else if(verificar == 1){
                        nombre = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
                        cantidad = 1;
                        try {
                            conexion.bd cbd = new bd();
                            cbd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                            cbd.setUsuario("root");
                            cbd.setContrasena("");
                            Connection con = cbd.getConexion();
                            Statement s = con.createStatement();
                            ResultSet rs = s.executeQuery("SELECT * FROM inventario WHERE ID = '"+jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()+"'");
                            if(rs.next()){
                                precio = rs.getString("precio");
                            }
                            rs.close();
                            //----------------------
                            conexion.bd cbd1 = new bd();
                            cbd1.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                            cbd1.setUsuario("root");
                            cbd1.setContrasena("");
                            Connection con1 = cbd1.getConexion();
                            Statement s1 = con.createStatement();
                            ResultSet rs1 = s1.executeQuery("SELECT * FROM guardar_compra WHERE nombre= '"+nombre+"'");
                            if(rs1.next()){
                                System.out.println("pantallas.de.menu.anubis.Ventas.CrearVenta.Ventas.jTable1MouseClicked()");
                            }else{
                                PreparedStatement pst;
                                try {
                                    pst = con1.prepareStatement("INSERT INTO guardar_compra(nombre, cantidad, precio) VALUES (?,?,?)");
                                    pst.setString(1, nombre);
                                    pst.setInt(2, cantidad);
                                    pst.setString(3, precio);
                                    pst.executeUpdate();
                                } catch (SQLException ex) {
                                    Logger.getLogger(Registrar_clientes.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                cargar_datos_de_compra();
                                verificar = 1;
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int column = jTable2.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTable2.getRowHeight();
        if(row<jTable2.getColumnCount() && row >= 0 && column < jTable2.getColumnCount() && column >=0){
            Object value = jTable2.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                if(boton.getName().equals("M")){
                    if(evt.getClickCount() == 2){
                        mv.jTextField3.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
                        mv.jTextField2.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
                        mv.setVisible(true);
                        verificar1 = 1;
                    }else if(verificar1 == 1){
                        mv.jTextField3.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
                        mv.jTextField2.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
                        mv.setVisible(true);
                    }
                }else if(boton.getName().equals("E")){
                    try {
                        String nombre = jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString();
                        conexion.bd cbd = new bd();
                        cbd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                        cbd.setUsuario("root");
                        cbd.setContrasena("");
                        Connection con = cbd.getConexion();
                        PreparedStatement pst = con.prepareStatement("DELETE FROM guardar_compra WHERE nombre='"+nombre+"'");
                        pst.executeUpdate();
                        total = 0;
                        cargar_datos_de_compra();
                    } catch (SQLException ex) {
                        Logger.getLogger(Empleados_menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(jComboBox2.getSelectedItem()!="SELECIONA EL MÉTODO DE PAGO")
        {   
            numero_fac = numero_fac + 1;
            
            if(jCheckBox1.isSelected()){
                Factura f = new Factura();
                f.jLabel4.setText("N°0"+numero_fac+" ");
                f.jLabel7.setText("CLIENTE: "+jComboBox1.getSelectedItem()+" ");
                try {
                    conexion.bd bd = new bd();
                    bd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                    bd.setUsuario("root");
                    bd.setContrasena("");
                    Connection con = bd.getConexion();
                    Statement s = con.createStatement();
                    ResultSet rs = s.executeQuery("SELECT * FROM clientes WHERE nombre='"+jComboBox1.getSelectedItem()+"'");
                    while(rs.next()){
                        f.jLabel5.setText("DIRRECION: "+rs.getString("dirrecion")+" ");
                        f.jLabel8.setText("TELEFONO: "+rs.getString("telefono")+" ");
                        f.jLabel12.setText("NIT O C.C: "+rs.getString("identificacion")+" ");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
                }
                f.jLabel6.setText("MUNICIPIO: MAGANGUÉ ");
                f.jLabel11.setText("FECHA: "+LocalDateTime.now().format(DateTimeFormatter.ISO_DATE)+" ");
                f.jLabel9.setText("VENDEDOR: "+jTextField1.getText()+" ");
                
                Locale locale2 = new Locale ("es", "US");
                NumberFormat objNF2 = NumberFormat.getInstance (locale2);
                String cadena2= objNF2.format(neto);
                f.jLabel10.setText("SUBTOTAL:         "+cadena2+" ");
                f.jLabel13.setText("DCTO: ");
                Locale locale3 = new Locale ("es", "US");
                NumberFormat objNF3 = NumberFormat.getInstance (locale3);
                String cadena3= objNF3.format((neto*19)/100);
                f.jLabel14.setText("IVA:                     "+cadena3+" ");
                Locale locale4 = new Locale ("es", "US");
                NumberFormat objNF4 = NumberFormat.getInstance (locale4);
                String cadena4= objNF4.format(total1);
                f.jLabel18.setText("TOTAL A PAGAR:  "+cadena4+" ");
                f.imprimir();
                f.cargar_pedidos();
                try {
                    Thread.sleep(2*1000);
                } catch (Exception e) {
                    System.out.println(e);
                }
                try {
                    conexion.bd cbd1 = new bd();
                    cbd1.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                    cbd1.setUsuario("root");
                    cbd1.setContrasena("");
                    Connection con1 = cbd1.getConexion();
                    PreparedStatement pst1;
                    pst1 = con1.prepareStatement("INSERT INTO administrarventa(codigo_factura, cliente, vendedor, formadepago, neto, total, fecha, factura) VALUES (?,?,?,?,?,?,?,?)");
                    pst1.setInt(1, numero_fac);
                    pst1.setString(2, jComboBox1.getSelectedItem().toString());
                    pst1.setString(3, jTextField1.getText());
                    pst1.setString(4, jComboBox2.getSelectedItem().toString());
                    pst1.setInt(5, neto);
                    pst1.setInt(6, total1);
                    pst1.setString(7, LocalDateTime.now().format(DateTimeFormatter.ISO_DATE));
                    try {
                        File archivo = new File("C://Users//braya//OneDrive//Documents//prueba.pdf");
                        FileInputStream fis = new FileInputStream(archivo);
                        pst1.setBlob(8, fis, (int) archivo.length());
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
                    }                    
                    pst1.executeUpdate();
                    total1=0;
                    neto=0;
                    
                    //actualiar cantidad de productos
                    try {
                        conexion.bd cbd_1 = new bd();
                        cbd_1.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                        cbd_1.setUsuario("root");
                        cbd_1.setContrasena("");
                        Connection con_1 = cbd_1.getConexion();
                        Statement s_1 = con_1.createStatement();
                        ResultSet rs_1 = s_1.executeQuery("SELECT * FROM guardar_compra");
                        //-------------------
                        conexion.bd cbd = new bd();
                        cbd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                        cbd.setUsuario("root");
                        cbd.setContrasena("");
                        Connection con = cbd.getConexion();
                        Statement s_2 = con.createStatement();
                        while(rs_1.next()){
                            ResultSet rs = s_2.executeQuery("SELECT * FROM inventario where nombre = '"+rs_1.getString("nombre")+"'");
                            if(rs.next()){
                                cantida_final = rs.getInt(4)-rs_1.getInt(3);                      
                                PreparedStatement pst = con.prepareStatement("UPDATE inventario SET cantidad='"+cantida_final+"' WHERE nombre='"+rs_1.getString("nombre")+"'");
                                pst.executeUpdate();
                            }   
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(modificar_empleados.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    //elimar guardar_producto
                    conexion.bd cbd = new bd();
                    cbd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                    cbd.setUsuario("root");
                    cbd.setContrasena("");
                    Connection con = cbd.getConexion();
                    PreparedStatement pst = con.prepareStatement("DELETE FROM guardar_compra");
                    pst.executeUpdate();
                    cargar_datos_de_compra();
                    CargarDatosDeProductos();
                } catch (SQLException ex) {
                    Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "ERROR AL MOMENTO DE REGISTRA EL PAGO PORFAVOR SELECIONAR UN METODO DE PAGO");
        }
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
    public void CargarDatosUsuario(String nombre, String contraseña){
        jTextField1.setText(nombre);
        jTextField2.setText(contraseña);
    }
    
    public void CargarDatosCliente(){
        jComboBox1.removeAllItems();
        if(datos_clientes_val == 0 || jTextField6.getText().equals("")){
            try {
                conexion.bd bd = new bd();
                bd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                bd.setUsuario("root");
                bd.setContrasena("");
                Connection con = bd.getConexion();
                Statement s = con.createStatement();
                ResultSet rs = s.executeQuery("SELECT * FROM clientes");
                while(rs.next()){
                    jComboBox1.addItem(rs.getString("nombre"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(datos_clientes_val == 1){
            try {
                conexion.bd bd = new bd();
                bd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                bd.setUsuario("root");
                bd.setContrasena("");
                Connection con = bd.getConexion();
                Statement s = con.createStatement();
                ResultSet rs = s.executeQuery("SELECT * FROM clientes WHERE identificacion = '"+jTextField6.getText()+"'");
                while(rs.next()){
                    jComboBox1.addItem(rs.getString("nombre"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
            }
            datos_clientes_val = 0;
        }
    }
    
    public void Cargar_Datos_Facturas(){
        jComboBox2.removeAllItems();
        jComboBox2.addItem("SELECIONA EL MÉTODO DE PAGO");
        jComboBox2.addItem("Efectivo");
        jComboBox2.addItem("Tarjeta Crédito");
        jComboBox2.addItem("Tarjeta Débito");
        jTextField3.setText("19");
    }
    
    public void CargarDatosDeProductos(){
        if(datos_de_productos_val == 0 || jTextField5.getText().equals("")){
            Object datos[] = new Object[5];
            dtm = new DefaultTableModel(){@Override
            public boolean isCellEditable(int row, int column){
                return false;
            }};
            dtm.addColumn("#");
            dtm.addColumn("Imagen");
            dtm.addColumn("Nombre");
            dtm.addColumn("Cantidad");
            dtm.addColumn("Acciones");
            jTable1.setModel(dtm);
            jTable1.setDefaultRenderer(Object.class, new Render());
            JButton btn1 = new JButton("AGREGAR");
            btn1.setName("A");

            //columna.setPreferredWidth(0);
            try {
                conexion.bd cbd = new bd();
                cbd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                cbd.setUsuario("root");
                cbd.setContrasena("");
                Connection con = cbd.getConexion();
                Statement s = con.createStatement();
                ResultSet rs = s.executeQuery("SELECT * FROM inventario");
                while(rs.next()){
                    datos[0] = rs.getString(1);
                    //imagen cominezo
                    JLabel jl = new JLabel();
                    InputStream is = rs.getBinaryStream(5);
                    BufferedImage bi = ImageIO.read(is);
                    ImageIcon li = new ImageIcon(bi);
                    jl.setSize(140, 120);
                    Icon icono = new ImageIcon(li.getImage().getScaledInstance(jl.getWidth(), jl.getHeight(), Image.SCALE_DEFAULT));
                    jl.setIcon(icono);
                    datos[1] = jl;
                    //imagen final
                    datos[2] = rs.getString(3);
                    datos[3] = rs.getInt(4);
                    datos[4] = btn1;
                    dtm.addRow(datos);
                }
                jTable1.setModel(dtm);
                jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                TableColumnModel colModel=jTable1.getColumnModel();
                colModel.getColumn(0).setPreferredWidth(25);
                colModel.getColumn(1).setPreferredWidth(150);
                colModel.getColumn(2).setPreferredWidth(400);
                colModel.getColumn(4).setPreferredWidth(140);
                jTable1.setRowHeight(120);

            } catch (SQLException ex) {
                Logger.getLogger(Empleados_menu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(datos_de_productos_val == 1){
            Object datos[] = new Object[5];
            dtm = new DefaultTableModel(){@Override
            public boolean isCellEditable(int row, int column){
                return false;
            }};
            dtm.addColumn("#");
            dtm.addColumn("Imagen");
            dtm.addColumn("Nombre");
            dtm.addColumn("Cantidad");
            dtm.addColumn("Acciones");
            jTable1.setModel(dtm);
            jTable1.setDefaultRenderer(Object.class, new Render());
            JButton btn1 = new JButton("AGREGAR");
            btn1.setName("A");

            //columna.setPreferredWidth(0);
            try {
                conexion.bd cbd = new bd();
                cbd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                cbd.setUsuario("root");
                cbd.setContrasena("");
                Connection con = cbd.getConexion();
                Statement s = con.createStatement();
                ResultSet rs = s.executeQuery("SELECT * FROM inventario WHERE nombre = '"+jTextField5.getText()+"'");
                while(rs.next()){
                    datos[0] = rs.getString(1);
                    //imagen cominezo
                    JLabel jl = new JLabel();
                    InputStream is = rs.getBinaryStream(5);
                    BufferedImage bi = ImageIO.read(is);
                    ImageIcon li = new ImageIcon(bi);
                    jl.setSize(140, 120);
                    Icon icono = new ImageIcon(li.getImage().getScaledInstance(jl.getWidth(), jl.getHeight(), Image.SCALE_DEFAULT));
                    jl.setIcon(icono);
                    datos[1] = jl;
                    //imagen final
                    datos[2] = rs.getString(3);
                    datos[3] = rs.getInt(4);
                    datos[4] = btn1;
                    dtm.addRow(datos);
                }
                jTable1.setModel(dtm);
                jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                TableColumnModel colModel=jTable1.getColumnModel();
                colModel.getColumn(0).setPreferredWidth(25);
                colModel.getColumn(1).setPreferredWidth(150);
                colModel.getColumn(2).setPreferredWidth(400);
                colModel.getColumn(4).setPreferredWidth(140);
                jTable1.setRowHeight(120);

            } catch (SQLException ex) {
                Logger.getLogger(Empleados_menu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void cargar_datos_de_compra(){
        if(verificar_productos == 0)
        {
            jTable2.setVisible(true);
            verificar_productos = 1;
        }
        Object datos[] = new Object[5];
            dtm2 = new DefaultTableModel(){@Override
            public boolean isCellEditable(int row, int column){
                return false;
            }};
            dtm2.addColumn("Eliminar");
            dtm2.addColumn("Modificar");
            dtm2.addColumn("Nombre");
            dtm2.addColumn("Cantidad");
            dtm2.addColumn("Precio");
            jTable2.setModel(dtm2);
            jTable2.setDefaultRenderer(Object.class, new Render());
            JButton btn1 = new JButton("ELIMINAR");
            btn1.setName("E");
            JButton btn2 = new JButton("MODIFICAR");
            btn2.setName("M");
            try {
                conexion.bd cbd = new bd();
                cbd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                cbd.setUsuario("root");
                cbd.setContrasena("");
                Connection con = cbd.getConexion();
                Statement s = con.createStatement();
                ResultSet rs = s.executeQuery("SELECT * FROM guardar_compra");
                while(rs.next()){
                   datos[0] = btn1;
                   datos[1] = btn2;
                   datos[2] = rs.getString(2);
                   datos[3] = rs.getInt(3);
                   Locale locale = new Locale ("es", "US");
                   NumberFormat objNF = NumberFormat.getInstance (locale);
                   String cadena= objNF.format(rs.getInt(4));
                   datos[4] = cadena;
                   total = total + (rs.getInt(4)*rs.getInt(3));
                   dtm2.addRow(datos);
                }
                jTable2.setModel(dtm2);
                jTable2.setRowHeight(30);
                neto = total;
                total = (int) (total * 1.19);
                total1 = total;
                System.out.println(total1);
                Locale locale = new Locale ("es", "US");
                NumberFormat objNF = NumberFormat.getInstance (locale);
                String cadena= objNF.format(total);
                jTextField4.setText(cadena);
                total=0;
            } catch (SQLException ex) {
                Logger.getLogger(Empleados_menu.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    public void ActualizarDatosDeVentas(){
        if(datos_clientes_val == 1){
            CargarDatosCliente();
            datos_clientes_val = 0;
        }
        if(rc.ins_dat_clientes == 1){
            CargarDatosCliente();
            rc.ins_dat_clientes = 0;
        }
        if(datos_de_productos_val == 1){
            CargarDatosDeProductos();
            datos_de_productos_val = 0;
        }
        if(mv.mod_dat_ventas_val == 1){
            cargar_datos_de_compra();
            mv.mod_dat_ventas_val = 0;
            total=0;
        }
    }
}
