/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas.de.menu.anubis.categorias;

import conexion.bd;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pantallas.de.menu.anubis.Empleados_menu;
import pantallas.de.menu.anubis.Render;

/**
 *
 * @author braya
 */
public class Categoria extends javax.swing.JInternalFrame {
    DefaultTableModel dtm;
    Registar_categoria rc = new Registar_categoria();
    Modificar_categorias mc = new Modificar_categorias();
    Thread hilo;
    int verificar = 0;
    /**
     * Creates new form Categoria
     */
    public Categoria() {
        initComponents();
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                // Esto se ejecuta en segundo plano una única vez
                while (true) {
                    // Pero usamos un truco y hacemos un ciclo infinito
                    try {
                        // En él, hacemos que el hilo duerma
                        Thread.sleep(1000);
                        // Y después realizamos las operaciones
                        actualizar_datos_de_categoria();
                        
                        // Así, se da la impresión de que se ejecuta cada cierto tiempo
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        // Creamos un hilo y le pasamos el runnable
        hilo = new Thread(runnable);
        hilo.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("REGISTRAR CATEGORIA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        rc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int column = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTable1.getRowHeight();
        if(row < jTable1.getRowCount() && row >= 0 && column < jTable1.getColumnCount() && column >= 0){
            Object value = jTable1.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                if(boton.getName().equals("M")){
                    if(evt.getClickCount() == 2){
                        mc.jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                        mc.jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                        mc.jTextField3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
                        mc.jTextField5.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
                        mc.setVisible(true);
                        verificar = 1;
                    }else if(verificar == 1){
                        mc.jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                        mc.jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                        mc.jTextField3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
                        mc.jTextField5.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
                    }
                }else if(boton.getName().equals("E")){
                    try {
                        int id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                        conexion.bd cbd = new bd();
                        cbd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
                        cbd.setUsuario("root");
                        cbd.setContrasena("");
                        Connection con = cbd.getConexion();
                        PreparedStatement pst = con.prepareStatement("DELETE FROM categorias WHERE id='"+id+"'");
                        pst.executeUpdate();
                        nombre_de_categoria();
                    } catch (SQLException ex) {
                        JOptionPane.showInternalMessageDialog(rootPane, "ERROR AL ELIMINAR CATEGORIA DE PRODUCTO VERIFICAR EN EL INVENTARIO QUE NO EXISTA PRODUCTO PARA ESTA CATEGORIA: "+jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                    }
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void nombre_de_categoria(){
        Object datos[] = new Object[6];
        dtm = new DefaultTableModel(){@Override public boolean isCellEditable(int row, int colum){
           return false;
        }};
        dtm.addColumn("#");
        dtm.addColumn("categoria");
        dtm.addColumn("color");
        dtm.addColumn("descripcion");
        dtm.addColumn("Modificar");
        dtm.addColumn("Eliminar");
        jTable1.setModel(dtm);
        jTable1.setDefaultRenderer(Object.class, new Render());
        JButton btn1 = new JButton("Modificar");
        btn1.setName("M");
        JButton btn2 = new JButton("Eliminar");
        btn2.setName("E");
        try {
            conexion.bd cbd = new bd();
            cbd.setServidor("jdbc:mysql://localhost/sistema_pos_anubis");
            cbd.setUsuario("root");
            cbd.setContrasena("");
            Connection con = cbd.getConexion();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM categorias");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = btn1;
                datos[5] = btn2;
                dtm.addRow(datos);
            }
            jTable1.setModel(dtm);
            jTable1.setRowHeight(30);
        } catch (SQLException ex) {
            Logger.getLogger(Empleados_menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void actualizar_datos_de_categoria(){
        if(rc.ins_dat_cat == 1){
            nombre_de_categoria();
            rc.ins_dat_cat = 0;
        }
        if(mc.mod_dat_categoria_val == 1){
            nombre_de_categoria();
            mc.mod_dat_categoria_val = 0;
        }
    }
    

}
